services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn constructmate.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: constructmate.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
