# Generated by Django 4.2.3 on 2024-08-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
