# Generated by Django 4.2.3 on 2024-08-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0002_alter_customer_details_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
