# Generated by Django 4.2.3 on 2024-08-28 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0003_project_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Building_type', models.CharField(max_length=50)),
                ('Land_area', models.FloatField()),
                ('Soil_type', models.CharField(max_length=50)),
                ('Soil_condition', models.CharField(max_length=50)),
                ('Materials', models.TextField()),
                ('Expectation', models.TextField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructapp.customer_details')),
            ],
        ),
    ]
