# Generated by Django 4.2.3 on 2024-08-30 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0004_project_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='qda_analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.TextField()),
                ('expectation', models.TextField()),
                ('insights', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructapp.project_manager')),
            ],
        ),
    ]
