# Generated by Django 4.2.3 on 2024-08-30 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0005_qda_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qda_analysis',
            name='material',
        ),
    ]
