# Generated by Django 4.2.3 on 2024-09-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0007_materialcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_area', models.FloatField()),
                ('material_quantities', models.JSONField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
