# Generated by Django 4.2.3 on 2024-09-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0008_constructiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard_quality_materialCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('cost_per_unit', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='MaterialCost',
            new_name='High_quality_materialCost',
        ),
    ]
