# Generated by Django 4.2.3 on 2024-09-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0009_standard_quality_materialcost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructiondata',
            name='materials_expectations',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
