# Generated by Django 4.2.3 on 2024-09-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0010_constructiondata_materials_expectations'),
    ]

    operations = [
        migrations.AddField(
            model_name='high_quality_materialcost',
            name='units',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='standard_quality_materialcost',
            name='units',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
