# Generated by Django 4.2.3 on 2024-09-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0012_manager_messenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager_messenger',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
