# Generated by Django 4.2.3 on 2024-09-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0013_manager_messenger_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='Status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='Materials',
            field=models.CharField(max_length=500),
        ),
    ]
