# Generated by Django 4.2.3 on 2024-09-03 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0014_project_details_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager_messenger_to_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='constructapp.customer_details')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_customer', to='constructapp.project_manager')),
            ],
        ),
        migrations.CreateModel(
            name='manager_messenger_to_vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendor_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='manager_messenger',
        ),
        migrations.AddField(
            model_name='manager_messenger_to_vendor',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='constructapp.vendor_details'),
        ),
        migrations.AddField(
            model_name='manager_messenger_to_vendor',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_vendor', to='constructapp.project_manager'),
        ),
    ]
