# Generated by Django 4.2.3 on 2024-09-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0015_manager_messenger_to_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='cost_report',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project_details',
            name='materials_report',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
