# Generated by Django 4.2.3 on 2024-09-04 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0016_project_details_cost_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_message_to_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='constructapp.project_manager')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_manager', to='constructapp.customer_details')),
            ],
        ),
    ]
