# Generated by Django 4.2.3 on 2024-09-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0017_customer_message_to_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='Reason',
            field=models.TextField(null=True),
        ),
    ]
