# Generated by Django 4.2.3 on 2024-09-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0018_project_details_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='Project_manager',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
