# Generated by Django 4.2.3 on 2024-09-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0019_project_details_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='quality_checker',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='vendor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
