# Generated by Django 4.2.3 on 2024-09-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0020_project_details_quality_checker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials_report_qc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cement_grade', models.CharField(max_length=10)),
                ('cement_quantity', models.CharField(max_length=10)),
                ('sand_grade', models.CharField(max_length=10)),
                ('sand_quantity', models.CharField(max_length=10)),
                ('aggregate_grade', models.CharField(max_length=10)),
                ('aggregate_quantity', models.CharField(max_length=10)),
                ('steel_grade', models.CharField(max_length=10)),
                ('steel_quantity', models.CharField(max_length=10)),
                ('paint_grade', models.CharField(max_length=10)),
                ('paint_quantity', models.CharField(max_length=10)),
                ('bricks_grade', models.CharField(max_length=10)),
                ('bricks_quantity', models.CharField(max_length=10)),
                ('tiles_grade', models.CharField(max_length=10)),
                ('tiles_quantity', models.CharField(max_length=10)),
                ('insulation_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('insulation_quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('adhesive_grade', models.CharField(max_length=10)),
                ('adhesive_quantity', models.CharField(max_length=10)),
                ('concrete_blocks_grade', models.CharField(max_length=10)),
                ('concrete_block_quantity', models.CharField(max_length=10)),
                ('wire_grade', models.CharField(max_length=10)),
                ('wire_quantity', models.CharField(max_length=10)),
                ('pipes_grade', models.CharField(max_length=10)),
                ('pipes_quantity', models.CharField(max_length=10)),
                ('wood_grade', models.CharField(max_length=10)),
                ('wood_quantity', models.CharField(max_length=10)),
                ('gravel', models.CharField(max_length=10)),
                ('gravel_quantity', models.CharField(max_length=10)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructapp.vendor_details')),
            ],
        ),
    ]
