# Generated by Django 4.2.3 on 2024-09-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0021_materials_report_qc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials_report_qc',
            old_name='gravel',
            new_name='electrical_wire_grade',
        ),
        migrations.RenameField(
            model_name='materials_report_qc',
            old_name='wire_grade',
            new_name='electrical_wire_quantity',
        ),
        migrations.RenameField(
            model_name='materials_report_qc',
            old_name='wire_quantity',
            new_name='gravel_grade',
        ),
    ]
