# Generated by Django 4.2.3 on 2024-09-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0022_rename_gravel_materials_report_qc_electrical_wire_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials_report_qc',
            name='project_id',
            field=models.IntegerField(null=True),
        ),
    ]
