# Generated by Django 4.2.3 on 2024-09-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0024_alter_materials_report_qc_project_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality_checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
