# Generated by Django 4.2.3 on 2024-09-06 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0025_quality_checker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quality_checker',
        ),
    ]
