# Generated by Django 4.2.3 on 2024-09-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0028_manager_to_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='supply_id',
            field=models.IntegerField(null=True),
        ),
    ]
