# Generated by Django 4.2.3 on 2024-09-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0029_project_details_supply_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConstructionData',
        ),
    ]
