# Generated by Django 4.2.3 on 2024-09-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0030_delete_constructiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_area', models.FloatField()),
                ('materials_expectations', models.CharField(max_length=100, null=True)),
                ('material_quantities', models.JSONField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructapp.customer_details')),
            ],
        ),
    ]
