# Generated by Django 4.2.3 on 2024-09-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0031_constructiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cement_quality', models.CharField(max_length=50)),
                ('sand_quality', models.CharField(max_length=50)),
                ('aggregate_quality', models.CharField(max_length=50)),
                ('steel_quality', models.CharField(max_length=50)),
                ('paint_quality', models.CharField(max_length=50)),
                ('bricks_quality', models.CharField(max_length=50)),
                ('tiles_quality', models.CharField(max_length=50)),
                ('insulation_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('adhesive_quality', models.CharField(max_length=50)),
                ('concrete_quality', models.CharField(max_length=50)),
                ('electrical_wire_quality', models.CharField(max_length=50)),
                ('pipes_quality', models.CharField(max_length=50)),
                ('wood_quality', models.CharField(max_length=50)),
                ('gravel_quality', models.CharField(max_length=50)),
                ('sufficient_materials', models.CharField(max_length=100, null=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('material_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='constructapp.materials_report_qc')),
            ],
        ),
    ]
