# Generated by Django 4.2.3 on 2024-09-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0032_qualityanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityanalysis',
            name='materials_quality',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='qualityanalysis',
            name='sufficient_materials',
            field=models.TextField(null=True),
        ),
    ]
