# Generated by Django 4.2.3 on 2024-09-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0036_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager_messenger_to_customer',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='manager_messenger_to_customer',
            name='sender',
        ),
        migrations.DeleteModel(
            name='customer_message_to_manager',
        ),
        migrations.DeleteModel(
            name='manager_messenger_to_customer',
        ),
    ]
