# Generated by Django 4.2.3 on 2024-09-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0037_remove_manager_messenger_to_customer_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
