# Generated by Django 4.2.3 on 2024-09-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0038_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='quality_check_report',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
