# Generated by Django 4.2.3 on 2024-09-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0039_project_details_quality_check_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='Address',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
