# Generated by Django 4.2.3 on 2024-09-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0040_project_details_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_details',
            name='Address',
            field=models.TextField(null=True),
        ),
    ]
