# Generated by Django 4.2.3 on 2024-09-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0041_alter_project_details_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='Address',
            field=models.TextField(null=True),
        ),
    ]
