# Generated by Django 4.2.3 on 2024-09-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0042_customer_details_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium_quality_materialCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('cost_per_unit', models.FloatField()),
                ('units', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
