# Generated by Django 4.2.3 on 2024-09-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0044_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_manager',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quality_checker',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor_details',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
