# Generated by Django 4.2.3 on 2024-09-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0045_project_manager_is_approve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_manager',
            name='is_approve',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='quality_checker',
            name='is_approve',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor_details',
            name='is_approve',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
