# Generated by Django 4.2.3 on 2024-09-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0046_alter_project_manager_is_approve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='Customer_confirmation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
