# Generated by Django 4.2.3 on 2024-09-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0047_project_details_customer_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='Password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project_manager',
            name='Password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quality_checker',
            name='Password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vendor_details',
            name='Password',
            field=models.CharField(max_length=500),
        ),
    ]
